### ISSUE TITLE
Create theme extractor rake task.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-themes-light#12]
For background, see this thread: https://twitter.com/andrewculver/status/1530571140476727297.

To start working on a theme, people can run `rake bullet_train:themes:light:eject[superdope]`. 

However, once they're happy with their theme, they should be able to extract it into a new Ruby gem and publish that.

To facilitate this, I want to propose a user could run `rake bullet_train:themes:light:release[superdope]`.

When they run this, the script:

- clones https://github.com/bullet-train-co/bullet_train/bullet_train-themes-light.
- prompts them to create a new private or public repository at https://github.com/repositories/new.
- prompts them for the git address of that repository.
- updates `git remote origin` to be the new repository.
- pushes to that repository.
- for the view paths, rename all directory or filename references to "light" to "superdope".
- for each view partial, check whether the file in the local repository is different than the one that was just cloned into the new Ruby gem repository from "light". If it's the same, just delete the file from the new "superdope" theme. It should be inherited from the "light" theme instead.
- if a "superdope" view partial was modified in in the local repository compared to the original "light" view partial, then we should copy it into place in the new clone "superdope" Ruby gem repository.
- copy configuration files and all other files into place in the new Ruby gem repository.
- remove all the light configuration files, etc. from the Ruby gem repository.
- update the `gemspec` to reflect the new Ruby gem name, etc.
- commit the new Ruby gem.
- push it to GitHub.
- remove all the theme files from the local repository.

**Comment by gazayas** [comment]
Making some progress.
Just for clarity, I'm assuming the end goal is to:
1. Put the custom gem in the main app's Gemfile and,
2. Run something like `rake bullet_train:themes:foo:eject` to eject the file to the developer's Bullet Train app.

The reason for 2 specifically being that, even if we've prepared everything in the gem, we still need to overwrite some of the main app's local files (like `Procfile.dev` and `package.json`). Running the eject command here will automatically set up everything the developer needs, but it will also include all of the files locally. Do we want that?

If not, we can write a different script that only replaces the main app's locals.

Either way I'm not quite that far yet, but I'll leave the comment here at least as a note to self.
